"""add compliance wizard tables

Revision ID: 78fe0fca9b0f
Revises: c3d4e5f67890
Create Date: 2025-12-13 04:05:26.806812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78fe0fca9b0f'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f67890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_templates',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('nace_codes', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_size', sa.String(length=20), nullable=True),
    sa.Column('activity_categories', sa.JSON(), nullable=False),
    sa.Column('smart_defaults', sa.JSON(), nullable=True),
    sa.Column('recommended_datasets', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industry_templates'))
    )
    op.create_table('compliance_wizard_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='wizardstatus'), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=False),
    sa.Column('company_profile', sa.JSON(), nullable=True),
    sa.Column('activity_data', sa.JSON(), nullable=True),
    sa.Column('calculated_emissions', sa.JSON(), nullable=True),
    sa.Column('template_id', sa.String(length=50), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_compliance_wizard_sessions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], name=op.f('fk_compliance_wizard_sessions_voucher_id_vouchers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_wizard_sessions'))
    )
    op.create_index('idx_wizard_sessions_tenant_status', 'compliance_wizard_sessions', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_wizard_sessions_tenant_voucher', 'compliance_wizard_sessions', ['tenant_id', 'voucher_id'], unique=False)
    op.create_index(op.f('ix_compliance_wizard_sessions_id'), 'compliance_wizard_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_wizard_sessions_report_id'), 'compliance_wizard_sessions', ['report_id'], unique=False)
    op.create_index(op.f('ix_compliance_wizard_sessions_status'), 'compliance_wizard_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_compliance_wizard_sessions_template_id'), 'compliance_wizard_sessions', ['template_id'], unique=False)
    op.create_index(op.f('ix_compliance_wizard_sessions_tenant_id'), 'compliance_wizard_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_compliance_wizard_sessions_voucher_id'), 'compliance_wizard_sessions', ['voucher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_wizard_sessions_voucher_id'), table_name='compliance_wizard_sessions')
    op.drop_index(op.f('ix_compliance_wizard_sessions_tenant_id'), table_name='compliance_wizard_sessions')
    op.drop_index(op.f('ix_compliance_wizard_sessions_template_id'), table_name='compliance_wizard_sessions')
    op.drop_index(op.f('ix_compliance_wizard_sessions_status'), table_name='compliance_wizard_sessions')
    op.drop_index(op.f('ix_compliance_wizard_sessions_report_id'), table_name='compliance_wizard_sessions')
    op.drop_index(op.f('ix_compliance_wizard_sessions_id'), table_name='compliance_wizard_sessions')
    op.drop_index('idx_wizard_sessions_tenant_voucher', table_name='compliance_wizard_sessions')
    op.drop_index('idx_wizard_sessions_tenant_status', table_name='compliance_wizard_sessions')
    op.drop_table('compliance_wizard_sessions')
    op.drop_table('industry_templates')
    # ### end Alembic commands ###
