"""production_schema_upgrade

Revision ID: 83e7815eabd8
Revises: 
Create Date: 2025-11-28 00:42:44.032631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83e7815eabd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('regulation', sa.String(length=50), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'category', 'activity_type', 'country_code', 'year', 'method', name='uq_emission_factor_lookup')
    )
    op.create_index('idx_factor_activity_type', 'emission_factors', ['activity_type'], unique=False)
    op.create_index('idx_factor_category', 'emission_factors', ['category'], unique=False)
    op.create_index('idx_factor_country_code', 'emission_factors', ['country_code'], unique=False)
    op.create_index('idx_factor_lookup', 'emission_factors', ['scope', 'category', 'activity_type', 'country_code'], unique=False)
    op.create_index('idx_factor_scope', 'emission_factors', ['scope'], unique=False)
    op.create_index(op.f('ix_emission_factors_activity_type'), 'emission_factors', ['activity_type'], unique=False)
    op.create_index(op.f('ix_emission_factors_category'), 'emission_factors', ['category'], unique=False)
    op.create_index(op.f('ix_emission_factors_country_code'), 'emission_factors', ['country_code'], unique=False)
    op.create_index(op.f('ix_emission_factors_id'), 'emission_factors', ['id'], unique=False)
    op.create_index(op.f('ix_emission_factors_scope'), 'emission_factors', ['scope'], unique=False)
    op.create_table('ghg_organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['ghg_organizations.id'], name=op.f('fk_ghg_organizations_organization_id_ghg_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ghg_organizations'))
    )
    op.create_table('ghg_reporting_periods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ghg_reporting_periods'))
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_session_id', sa.String(), nullable=True),
    sa.Column('stripe_payment_intent', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_customer_email'), 'payments', ['customer_email'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_intent'), 'payments', ['stripe_payment_intent'], unique=True)
    op.create_index(op.f('ix_payments_stripe_session_id'), 'payments', ['stripe_session_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('emissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.Enum('SCOPE_1', 'SCOPE_2', 'SCOPE_3', name='emissionscope'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('activity_data', sa.Float(), nullable=False, comment='Quantity of activity (e.g., kWh, km, kg)'),
    sa.Column('unit', sa.String(length=50), nullable=False, comment='Unit of measurement for activity'),
    sa.Column('emission_factor', sa.Float(), nullable=True, comment='Emission factor used (kgCO2e per unit)'),
    sa.Column('emission_factor_source', sa.String(length=200), nullable=True, comment='Source of emission factor'),
    sa.Column('amount', sa.Float(), nullable=False, comment='Calculated emission amount in tCO2e'),
    sa.Column('data_source', sa.Enum('MEASURED', 'CALCULATED', 'ESTIMATED', 'DEFAULT', name='datasourcetype'), nullable=True),
    sa.Column('data_quality_score', sa.Integer(), nullable=True, comment='Data quality score 1-100'),
    sa.Column('uncertainty_percentage', sa.Float(), nullable=True, comment='Uncertainty percentage'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='Location/facility name'),
    sa.Column('country_code', sa.String(length=2), nullable=True, comment='ISO country code'),
    sa.Column('reporting_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reporting_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True, comment='Comma-separated tags'),
    sa.Column('external_reference', sa.String(length=200), nullable=True, comment='External system reference'),
    sa.Column('is_verified', sa.Integer(), nullable=True, comment='0=unverified, 1=verified'),
    sa.Column('verified_by', sa.String(length=200), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emissions_created_at', 'emissions', ['created_at'], unique=False)
    op.create_index('idx_emissions_reporting_period', 'emissions', ['reporting_period_start', 'reporting_period_end'], unique=False)
    op.create_index('idx_emissions_user_scope', 'emissions', ['user_id', 'scope'], unique=False)
    op.create_index(op.f('ix_emissions_category'), 'emissions', ['category'], unique=False)
    op.create_index(op.f('ix_emissions_id'), 'emissions', ['id'], unique=False)
    op.create_index(op.f('ix_emissions_scope'), 'emissions', ['scope'], unique=False)
    op.create_table('ghg_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['ghg_organizations.id'], name=op.f('fk_ghg_audit_logs_organization_id_ghg_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ghg_audit_logs'))
    )
    op.create_table('ghg_calculation_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('reporting_period_start', sa.DateTime(), nullable=False),
    sa.Column('reporting_period_end', sa.DateTime(), nullable=False),
    sa.Column('total_emissions', sa.Float(), nullable=True),
    sa.Column('calculation_method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('uncertainty_min', sa.Float(), nullable=True),
    sa.Column('uncertainty_max', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['ghg_organizations.id'], name=op.f('fk_ghg_calculation_results_organization_id_ghg_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ghg_calculation_results'))
    )
    op.create_table('ghg_data_quality_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('calculation_id', sa.String(length=36), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('criteria', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['ghg_organizations.id'], name=op.f('fk_ghg_data_quality_scores_organization_id_ghg_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ghg_data_quality_scores'))
    )
    op.create_table('ghg_emission_factors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('factor_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('uncertainty_percentage', sa.Float(), nullable=True),
    sa.Column('factor_emission_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['ghg_organizations.id'], name=op.f('fk_ghg_emission_factors_organization_id_ghg_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ghg_emission_factors'))
    )
    op.create_index('idx_category_region', 'ghg_emission_factors', ['category', 'region'], unique=False)
    op.create_table('ghg_scope3_inventories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_scope3_emissions', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['ghg_organizations.id'], name=op.f('fk_ghg_scope3_inventories_organization_id_ghg_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ghg_scope3_inventories'))
    )
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('company_email', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('VALID', 'USED', 'EXPIRED', 'REVOKED', name='voucherstatus'), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('report_generation_in_progress', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.String(), nullable=True),
    sa.Column('total_uses', sa.Integer(), nullable=True),
    sa.Column('remaining_uses', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vouchers_code'), 'vouchers', ['code'], unique=True)
    op.create_index(op.f('ix_vouchers_company_email'), 'vouchers', ['company_email'], unique=False)
    op.create_index(op.f('ix_vouchers_id'), 'vouchers', ['id'], unique=False)
    op.create_table('data_quality_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emission_id', sa.Integer(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('timeliness_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('assessment_details', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emission_id'], ['emissions.id'], name=op.f('fk_data_quality_scores_emission_id_emissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_scores'))
    )
    op.create_index(op.f('ix_data_quality_scores_id'), 'data_quality_scores', ['id'], unique=False)
    op.create_table('evidence_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emission_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['emission_id'], ['emissions.id'], name=op.f('fk_evidence_documents_emission_id_emissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_documents'))
    )
    op.create_index(op.f('ix_evidence_documents_id'), 'evidence_documents', ['id'], unique=False)
    op.create_table('ghg_activity_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('calculation_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['calculation_id'], ['ghg_calculation_results.id'], name=op.f('fk_ghg_activity_data_calculation_id_ghg_calculation_results')),
    sa.ForeignKeyConstraint(['organization_id'], ['ghg_organizations.id'], name=op.f('fk_ghg_activity_data_organization_id_ghg_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ghg_activity_data'))
    )
    op.create_table('ghg_category_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('calculation_id', sa.String(length=36), nullable=True),
    sa.Column('emissions_co2e', sa.Float(), nullable=False),
    sa.Column('calculation_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['calculation_id'], ['ghg_calculation_results.id'], name=op.f('fk_ghg_category_results_calculation_id_ghg_calculation_results')),
    sa.ForeignKeyConstraint(['organization_id'], ['ghg_organizations.id'], name=op.f('fk_ghg_category_results_organization_id_ghg_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ghg_category_results'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ghg_category_results')
    op.drop_table('ghg_activity_data')
    op.drop_index(op.f('ix_evidence_documents_id'), table_name='evidence_documents')
    op.drop_table('evidence_documents')
    op.drop_index(op.f('ix_data_quality_scores_id'), table_name='data_quality_scores')
    op.drop_table('data_quality_scores')
    op.drop_index(op.f('ix_vouchers_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_company_email'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_code'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_table('ghg_scope3_inventories')
    op.drop_index('idx_category_region', table_name='ghg_emission_factors')
    op.drop_table('ghg_emission_factors')
    op.drop_table('ghg_data_quality_scores')
    op.drop_table('ghg_calculation_results')
    op.drop_table('ghg_audit_logs')
    op.drop_index(op.f('ix_emissions_scope'), table_name='emissions')
    op.drop_index(op.f('ix_emissions_id'), table_name='emissions')
    op.drop_index(op.f('ix_emissions_category'), table_name='emissions')
    op.drop_index('idx_emissions_user_scope', table_name='emissions')
    op.drop_index('idx_emissions_reporting_period', table_name='emissions')
    op.drop_index('idx_emissions_created_at', table_name='emissions')
    op.drop_table('emissions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_payments_stripe_session_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_stripe_payment_intent'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_email'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('ghg_reporting_periods')
    op.drop_table('ghg_organizations')
    op.drop_index(op.f('ix_emission_factors_scope'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_id'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_country_code'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_category'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_activity_type'), table_name='emission_factors')
    op.drop_index('idx_factor_scope', table_name='emission_factors')
    op.drop_index('idx_factor_lookup', table_name='emission_factors')
    op.drop_index('idx_factor_country_code', table_name='emission_factors')
    op.drop_index('idx_factor_category', table_name='emission_factors')
    op.drop_index('idx_factor_activity_type', table_name='emission_factors')
    op.drop_table('emission_factors')
    # ### end Alembic commands ###
