"""add_issb_tables

Revision ID: f1eda72e46c2
Revises: b2c3d4e5f678
Create Date: 2025-12-12 20:37:00.435427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1eda72e46c2'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issb_reporting_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='ISO 4217 currency code'),
    sa.Column('consolidation_method', sa.Enum('FULL', 'EQUITY', 'PROPORTIONATE', name='issbconsolidationmethod'), nullable=False),
    sa.Column('parent_unit_id', sa.Integer(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry_code', sa.String(length=20), nullable=True, comment='NACE/NAICS code'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_unit_id'], ['issb_reporting_units.id'], name=op.f('fk_issb_reporting_units_parent_unit_id_issb_reporting_units'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_issb_reporting_units_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issb_reporting_units'))
    )
    op.create_index('idx_issb_unit_tenant_active', 'issb_reporting_units', ['tenant_id', 'is_active'], unique=False)
    op.create_index('idx_issb_unit_tenant_name', 'issb_reporting_units', ['tenant_id', 'name'], unique=False)
    op.create_index('idx_issb_unit_tenant_parent', 'issb_reporting_units', ['tenant_id', 'parent_unit_id'], unique=False)
    op.create_index(op.f('ix_issb_reporting_units_id'), 'issb_reporting_units', ['id'], unique=False)
    op.create_index(op.f('ix_issb_reporting_units_parent_unit_id'), 'issb_reporting_units', ['parent_unit_id'], unique=False)
    op.create_index(op.f('ix_issb_reporting_units_tenant_id'), 'issb_reporting_units', ['tenant_id'], unique=False)
    op.create_table('issb_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('temperature_pathway', sa.String(length=20), nullable=False, comment="e.g., '1.5C', '2C', '3C'"),
    sa.Column('reference_source', sa.String(length=200), nullable=True, comment="e.g., 'NGFS Current Policies', 'IEA Net Zero 2050'"),
    sa.Column('carbon_price_path_json', sa.JSON(), nullable=True, comment='Year to carbon price mapping, e.g., {2025: 60, 2030: 100}'),
    sa.Column('policy_assumptions', sa.Text(), nullable=True),
    sa.Column('market_assumptions', sa.Text(), nullable=True),
    sa.Column('technology_assumptions', sa.Text(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='Default scenario for tenant'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_issb_scenarios_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issb_scenarios'))
    )
    op.create_index('idx_issb_scenario_tenant_default', 'issb_scenarios', ['tenant_id', 'is_default'], unique=False)
    op.create_index('idx_issb_scenario_tenant_name', 'issb_scenarios', ['tenant_id', 'name'], unique=False)
    op.create_index('idx_issb_scenario_tenant_temp', 'issb_scenarios', ['tenant_id', 'temperature_pathway'], unique=False)
    op.create_index(op.f('ix_issb_scenarios_id'), 'issb_scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_issb_scenarios_tenant_id'), 'issb_scenarios', ['tenant_id'], unique=False)
    op.create_table('issb_climate_risk_exposures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('reporting_unit_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_type', sa.Enum('PHYSICAL', 'TRANSITION', name='issbrisktype'), nullable=False, comment='Physical or Transition risk'),
    sa.Column('subtype', sa.String(length=50), nullable=True, comment='E.g., acute/chronic for physical; policy/technology/market for transition'),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('time_horizon', sa.Enum('SHORT', 'MEDIUM', 'LONG', name='issbtimehorizon'), nullable=False),
    sa.Column('financial_impact_type', sa.Enum('REVENUE_DOWNSIDE', 'REVENUE_UPSIDE', 'COST_UPSIDE', 'COST_DOWNSIDE', 'ASSET_IMPAIRMENT', 'STRANDED_ASSETS', 'CAPEX_REQUIREMENT', 'INSURANCE_COST', name='issbfinancialimpacttype'), nullable=True),
    sa.Column('impact_range_low', sa.Float(), nullable=True, comment='Low estimate of financial impact'),
    sa.Column('impact_range_high', sa.Float(), nullable=True, comment='High estimate of financial impact'),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('qualitative_likelihood', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='issblikelihood'), nullable=True),
    sa.Column('linked_to_emissions', sa.Boolean(), nullable=True),
    sa.Column('linked_scope', sa.Enum('SCOPE1', 'SCOPE2', 'SCOPE3', 'COMBINED', 'MIXED', name='issbemissionsscope'), nullable=True, comment='Which emissions scope this risk relates to'),
    sa.Column('mitigation_strategy', sa.Text(), nullable=True),
    sa.Column('is_mitigated', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reporting_unit_id'], ['issb_reporting_units.id'], name=op.f('fk_issb_climate_risk_exposures_reporting_unit_id_issb_reporting_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_issb_climate_risk_exposures_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issb_climate_risk_exposures'))
    )
    op.create_index('idx_issb_risk_tenant_horizon', 'issb_climate_risk_exposures', ['tenant_id', 'time_horizon'], unique=False)
    op.create_index('idx_issb_risk_tenant_type', 'issb_climate_risk_exposures', ['tenant_id', 'risk_type'], unique=False)
    op.create_index('idx_issb_risk_tenant_unit', 'issb_climate_risk_exposures', ['tenant_id', 'reporting_unit_id'], unique=False)
    op.create_index('idx_issb_risk_unit_type_horizon', 'issb_climate_risk_exposures', ['reporting_unit_id', 'risk_type', 'time_horizon'], unique=False)
    op.create_index(op.f('ix_issb_climate_risk_exposures_id'), 'issb_climate_risk_exposures', ['id'], unique=False)
    op.create_index(op.f('ix_issb_climate_risk_exposures_reporting_unit_id'), 'issb_climate_risk_exposures', ['reporting_unit_id'], unique=False)
    op.create_index(op.f('ix_issb_climate_risk_exposures_risk_type'), 'issb_climate_risk_exposures', ['risk_type'], unique=False)
    op.create_index(op.f('ix_issb_climate_risk_exposures_tenant_id'), 'issb_climate_risk_exposures', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_issb_climate_risk_exposures_time_horizon'), 'issb_climate_risk_exposures', ['time_horizon'], unique=False)
    op.create_table('issb_disclosure_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('reporting_unit_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('standard', sa.Enum('IFRS_S1', 'IFRS_S2', name='issbdisclosurestandard'), nullable=False),
    sa.Column('section', sa.Enum('GOVERNANCE', 'STRATEGY', 'RISK_MANAGEMENT', 'METRICS_TARGETS', name='issbdisclosuresection'), nullable=False),
    sa.Column('headline_summary', sa.String(length=500), nullable=True, comment='Short summary for executive view'),
    sa.Column('body_markdown', sa.Text(), nullable=True, comment='Full disclosure in markdown format'),
    sa.Column('body_html', sa.Text(), nullable=True, comment='Rendered HTML version'),
    sa.Column('generated_by_system', sa.Boolean(), nullable=True),
    sa.Column('generation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('template_version', sa.String(length=20), nullable=True),
    sa.Column('last_edited_by', sa.String(length=200), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edit_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'ARCHIVED', name='issbdisclosurestatus'), nullable=False),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reporting_unit_id'], ['issb_reporting_units.id'], name=op.f('fk_issb_disclosure_statements_reporting_unit_id_issb_reporting_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_issb_disclosure_statements_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issb_disclosure_statements'))
    )
    op.create_index('idx_issb_disclosure_tenant_section', 'issb_disclosure_statements', ['tenant_id', 'section'], unique=False)
    op.create_index('idx_issb_disclosure_tenant_standard', 'issb_disclosure_statements', ['tenant_id', 'standard'], unique=False)
    op.create_index('idx_issb_disclosure_tenant_status', 'issb_disclosure_statements', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_issb_disclosure_tenant_unit', 'issb_disclosure_statements', ['tenant_id', 'reporting_unit_id'], unique=False)
    op.create_index('idx_issb_disclosure_unit_period', 'issb_disclosure_statements', ['reporting_unit_id', 'period_start', 'period_end'], unique=False)
    op.create_index('idx_issb_disclosure_unit_section', 'issb_disclosure_statements', ['reporting_unit_id', 'section', 'standard'], unique=False)
    op.create_index(op.f('ix_issb_disclosure_statements_id'), 'issb_disclosure_statements', ['id'], unique=False)
    op.create_index(op.f('ix_issb_disclosure_statements_reporting_unit_id'), 'issb_disclosure_statements', ['reporting_unit_id'], unique=False)
    op.create_index(op.f('ix_issb_disclosure_statements_section'), 'issb_disclosure_statements', ['section'], unique=False)
    op.create_index(op.f('ix_issb_disclosure_statements_standard'), 'issb_disclosure_statements', ['standard'], unique=False)
    op.create_index(op.f('ix_issb_disclosure_statements_status'), 'issb_disclosure_statements', ['status'], unique=False)
    op.create_index(op.f('ix_issb_disclosure_statements_tenant_id'), 'issb_disclosure_statements', ['tenant_id'], unique=False)
    op.create_table('issb_financial_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('reporting_unit_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_type', sa.Enum('REVENUE', 'EBITDA', 'EBIT', 'CAPEX', 'OPEX', 'ASSETS', 'LIABILITIES', 'CARBON_PRICE_EXPOSURE', 'NET_INCOME', 'FREE_CASH_FLOW', name='issbmetrictype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('segment', sa.String(length=100), nullable=True, comment='Product line/geography'),
    sa.Column('is_audited', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True, comment='Source document/system'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reporting_unit_id'], ['issb_reporting_units.id'], name=op.f('fk_issb_financial_metrics_reporting_unit_id_issb_reporting_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_issb_financial_metrics_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issb_financial_metrics'))
    )
    op.create_index('idx_issb_metric_tenant_period', 'issb_financial_metrics', ['tenant_id', 'period_start', 'period_end'], unique=False)
    op.create_index('idx_issb_metric_tenant_type', 'issb_financial_metrics', ['tenant_id', 'metric_type'], unique=False)
    op.create_index('idx_issb_metric_tenant_unit', 'issb_financial_metrics', ['tenant_id', 'reporting_unit_id'], unique=False)
    op.create_index('idx_issb_metric_unit_type_period', 'issb_financial_metrics', ['reporting_unit_id', 'metric_type', 'period_start'], unique=False)
    op.create_index(op.f('ix_issb_financial_metrics_id'), 'issb_financial_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_issb_financial_metrics_metric_type'), 'issb_financial_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_issb_financial_metrics_period_start'), 'issb_financial_metrics', ['period_start'], unique=False)
    op.create_index(op.f('ix_issb_financial_metrics_reporting_unit_id'), 'issb_financial_metrics', ['reporting_unit_id'], unique=False)
    op.create_index(op.f('ix_issb_financial_metrics_tenant_id'), 'issb_financial_metrics', ['tenant_id'], unique=False)
    op.create_table('issb_materiality_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('reporting_unit_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('topic', sa.Enum('CLIMATE', 'WATER', 'BIODIVERSITY', 'CIRCULAR_ECONOMY', 'POLLUTION', 'WORKFORCE', name='issbmaterialitytopic'), nullable=False),
    sa.Column('impact_materiality_score', sa.Float(), nullable=True, comment='Impact on environment/society (0-100)'),
    sa.Column('financial_materiality_score', sa.Float(), nullable=True, comment='Impact on financial performance (0-100)'),
    sa.Column('material', sa.Boolean(), nullable=True, comment='Is topic material?'),
    sa.Column('materiality_threshold', sa.Float(), nullable=True, comment='Threshold used for determination'),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('methodology_reference', sa.String(length=200), nullable=True, comment="e.g., '2D matrix', 'multi-criteria'"),
    sa.Column('emissions_total_tco2e', sa.Float(), nullable=True),
    sa.Column('revenue_total', sa.Float(), nullable=True),
    sa.Column('revenue_exposed', sa.Float(), nullable=True, comment='Revenue exposed to climate risk'),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reporting_unit_id'], ['issb_reporting_units.id'], name=op.f('fk_issb_materiality_assessments_reporting_unit_id_issb_reporting_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_issb_materiality_assessments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issb_materiality_assessments'))
    )
    op.create_index('idx_issb_materiality_tenant_topic', 'issb_materiality_assessments', ['tenant_id', 'topic'], unique=False)
    op.create_index('idx_issb_materiality_tenant_unit', 'issb_materiality_assessments', ['tenant_id', 'reporting_unit_id'], unique=False)
    op.create_index('idx_issb_materiality_unit_period', 'issb_materiality_assessments', ['reporting_unit_id', 'period_start', 'period_end'], unique=False)
    op.create_index(op.f('ix_issb_materiality_assessments_id'), 'issb_materiality_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_issb_materiality_assessments_reporting_unit_id'), 'issb_materiality_assessments', ['reporting_unit_id'], unique=False)
    op.create_index(op.f('ix_issb_materiality_assessments_tenant_id'), 'issb_materiality_assessments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_issb_materiality_assessments_topic'), 'issb_materiality_assessments', ['topic'], unique=False)
    op.create_table('issb_scenario_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('reporting_unit_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('projection_year', sa.Integer(), nullable=True, comment='Specific year for projection'),
    sa.Column('metric_type', sa.Enum('REVENUE', 'EBITDA', 'COST_OF_CARBON', 'CAPEX_REQUIRED', 'STRANDED_ASSETS', 'MARGIN_IMPACT', 'REVENUE_AT_RISK', name='issbscenarioresultmetric'), nullable=False),
    sa.Column('base_case_value', sa.Float(), nullable=True, comment='Value without scenario impact'),
    sa.Column('scenario_value', sa.Float(), nullable=True, comment='Value with scenario impact'),
    sa.Column('delta_value', sa.Float(), nullable=True, comment='Difference (scenario - base)'),
    sa.Column('delta_percentage', sa.Float(), nullable=True, comment='Percentage change'),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('calculation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('carbon_price_used', sa.Float(), nullable=True, comment='Carbon price used for calculation'),
    sa.Column('emissions_used', sa.Float(), nullable=True, comment='tCO2e used for calculation'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['reporting_unit_id'], ['issb_reporting_units.id'], name=op.f('fk_issb_scenario_results_reporting_unit_id_issb_reporting_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['issb_scenarios.id'], name=op.f('fk_issb_scenario_results_scenario_id_issb_scenarios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_issb_scenario_results_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issb_scenario_results'))
    )
    op.create_index('idx_issb_result_scenario_unit_metric', 'issb_scenario_results', ['scenario_id', 'reporting_unit_id', 'metric_type'], unique=False)
    op.create_index('idx_issb_result_tenant_scenario', 'issb_scenario_results', ['tenant_id', 'scenario_id'], unique=False)
    op.create_index('idx_issb_result_tenant_unit', 'issb_scenario_results', ['tenant_id', 'reporting_unit_id'], unique=False)
    op.create_index('idx_issb_result_tenant_year', 'issb_scenario_results', ['tenant_id', 'projection_year'], unique=False)
    op.create_index(op.f('ix_issb_scenario_results_id'), 'issb_scenario_results', ['id'], unique=False)
    op.create_index(op.f('ix_issb_scenario_results_metric_type'), 'issb_scenario_results', ['metric_type'], unique=False)
    op.create_index(op.f('ix_issb_scenario_results_reporting_unit_id'), 'issb_scenario_results', ['reporting_unit_id'], unique=False)
    op.create_index(op.f('ix_issb_scenario_results_scenario_id'), 'issb_scenario_results', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_issb_scenario_results_tenant_id'), 'issb_scenario_results', ['tenant_id'], unique=False)
    op.create_table('issb_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('reporting_unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_type', sa.Enum('ABSOLUTE_EMISSIONS', 'EMISSIONS_INTENSITY', 'RENEWABLES_SHARE', 'CAPEX_ALIGNMENT', 'NET_ZERO', 'SCIENCE_BASED', name='issbtargettype'), nullable=False),
    sa.Column('scope', sa.Enum('SCOPE1', 'SCOPE2', 'SCOPE3', 'COMBINED', 'MIXED', name='issbemissionsscope'), nullable=True, comment='Emissions scope if applicable'),
    sa.Column('base_year', sa.Integer(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('base_value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True, comment='Most recent actual value'),
    sa.Column('unit', sa.String(length=50), nullable=False, comment='e.g., tCO2e, tCO2e/revenue, %'),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'ON_TRACK', 'OFF_TRACK', 'ACHIEVED', 'ABANDONED', name='issbtargetstatus'), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=True, comment='0-100%'),
    sa.Column('is_sbti_validated', sa.Boolean(), nullable=True, comment='Science Based Targets initiative validated'),
    sa.Column('validation_body', sa.String(length=100), nullable=True),
    sa.Column('validation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reporting_unit_id'], ['issb_reporting_units.id'], name=op.f('fk_issb_targets_reporting_unit_id_issb_reporting_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_issb_targets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issb_targets'))
    )
    op.create_index('idx_issb_target_tenant_status', 'issb_targets', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_issb_target_tenant_type', 'issb_targets', ['tenant_id', 'target_type'], unique=False)
    op.create_index('idx_issb_target_tenant_unit', 'issb_targets', ['tenant_id', 'reporting_unit_id'], unique=False)
    op.create_index('idx_issb_target_unit_year', 'issb_targets', ['reporting_unit_id', 'target_year'], unique=False)
    op.create_index(op.f('ix_issb_targets_id'), 'issb_targets', ['id'], unique=False)
    op.create_index(op.f('ix_issb_targets_reporting_unit_id'), 'issb_targets', ['reporting_unit_id'], unique=False)
    op.create_index(op.f('ix_issb_targets_status'), 'issb_targets', ['status'], unique=False)
    op.create_index(op.f('ix_issb_targets_target_type'), 'issb_targets', ['target_type'], unique=False)
    op.create_index(op.f('ix_issb_targets_target_year'), 'issb_targets', ['target_year'], unique=False)
    op.create_index(op.f('ix_issb_targets_tenant_id'), 'issb_targets', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop ISSB targets
    op.drop_index(op.f('ix_issb_targets_tenant_id'), table_name='issb_targets')
    op.drop_index(op.f('ix_issb_targets_target_year'), table_name='issb_targets')
    op.drop_index(op.f('ix_issb_targets_target_type'), table_name='issb_targets')
    op.drop_index(op.f('ix_issb_targets_status'), table_name='issb_targets')
    op.drop_index(op.f('ix_issb_targets_reporting_unit_id'), table_name='issb_targets')
    op.drop_index(op.f('ix_issb_targets_id'), table_name='issb_targets')
    op.drop_index('idx_issb_target_unit_year', table_name='issb_targets')
    op.drop_index('idx_issb_target_tenant_unit', table_name='issb_targets')
    op.drop_index('idx_issb_target_tenant_type', table_name='issb_targets')
    op.drop_index('idx_issb_target_tenant_status', table_name='issb_targets')
    op.drop_table('issb_targets')
    op.drop_index(op.f('ix_issb_scenario_results_tenant_id'), table_name='issb_scenario_results')
    op.drop_index(op.f('ix_issb_scenario_results_scenario_id'), table_name='issb_scenario_results')
    op.drop_index(op.f('ix_issb_scenario_results_reporting_unit_id'), table_name='issb_scenario_results')
    op.drop_index(op.f('ix_issb_scenario_results_metric_type'), table_name='issb_scenario_results')
    op.drop_index(op.f('ix_issb_scenario_results_id'), table_name='issb_scenario_results')
    op.drop_index('idx_issb_result_tenant_year', table_name='issb_scenario_results')
    op.drop_index('idx_issb_result_tenant_unit', table_name='issb_scenario_results')
    op.drop_index('idx_issb_result_tenant_scenario', table_name='issb_scenario_results')
    op.drop_index('idx_issb_result_scenario_unit_metric', table_name='issb_scenario_results')
    op.drop_table('issb_scenario_results')
    op.drop_index(op.f('ix_issb_materiality_assessments_topic'), table_name='issb_materiality_assessments')
    op.drop_index(op.f('ix_issb_materiality_assessments_tenant_id'), table_name='issb_materiality_assessments')
    op.drop_index(op.f('ix_issb_materiality_assessments_reporting_unit_id'), table_name='issb_materiality_assessments')
    op.drop_index(op.f('ix_issb_materiality_assessments_id'), table_name='issb_materiality_assessments')
    op.drop_index('idx_issb_materiality_unit_period', table_name='issb_materiality_assessments')
    op.drop_index('idx_issb_materiality_tenant_unit', table_name='issb_materiality_assessments')
    op.drop_index('idx_issb_materiality_tenant_topic', table_name='issb_materiality_assessments')
    op.drop_table('issb_materiality_assessments')
    op.drop_index(op.f('ix_issb_financial_metrics_tenant_id'), table_name='issb_financial_metrics')
    op.drop_index(op.f('ix_issb_financial_metrics_reporting_unit_id'), table_name='issb_financial_metrics')
    op.drop_index(op.f('ix_issb_financial_metrics_period_start'), table_name='issb_financial_metrics')
    op.drop_index(op.f('ix_issb_financial_metrics_metric_type'), table_name='issb_financial_metrics')
    op.drop_index(op.f('ix_issb_financial_metrics_id'), table_name='issb_financial_metrics')
    op.drop_index('idx_issb_metric_unit_type_period', table_name='issb_financial_metrics')
    op.drop_index('idx_issb_metric_tenant_unit', table_name='issb_financial_metrics')
    op.drop_index('idx_issb_metric_tenant_type', table_name='issb_financial_metrics')
    op.drop_index('idx_issb_metric_tenant_period', table_name='issb_financial_metrics')
    op.drop_table('issb_financial_metrics')
    op.drop_index(op.f('ix_issb_disclosure_statements_tenant_id'), table_name='issb_disclosure_statements')
    op.drop_index(op.f('ix_issb_disclosure_statements_status'), table_name='issb_disclosure_statements')
    op.drop_index(op.f('ix_issb_disclosure_statements_standard'), table_name='issb_disclosure_statements')
    op.drop_index(op.f('ix_issb_disclosure_statements_section'), table_name='issb_disclosure_statements')
    op.drop_index(op.f('ix_issb_disclosure_statements_reporting_unit_id'), table_name='issb_disclosure_statements')
    op.drop_index(op.f('ix_issb_disclosure_statements_id'), table_name='issb_disclosure_statements')
    op.drop_index('idx_issb_disclosure_unit_section', table_name='issb_disclosure_statements')
    op.drop_index('idx_issb_disclosure_unit_period', table_name='issb_disclosure_statements')
    op.drop_index('idx_issb_disclosure_tenant_unit', table_name='issb_disclosure_statements')
    op.drop_index('idx_issb_disclosure_tenant_status', table_name='issb_disclosure_statements')
    op.drop_index('idx_issb_disclosure_tenant_standard', table_name='issb_disclosure_statements')
    op.drop_index('idx_issb_disclosure_tenant_section', table_name='issb_disclosure_statements')
    op.drop_table('issb_disclosure_statements')
    op.drop_index(op.f('ix_issb_climate_risk_exposures_time_horizon'), table_name='issb_climate_risk_exposures')
    op.drop_index(op.f('ix_issb_climate_risk_exposures_tenant_id'), table_name='issb_climate_risk_exposures')
    op.drop_index(op.f('ix_issb_climate_risk_exposures_risk_type'), table_name='issb_climate_risk_exposures')
    op.drop_index(op.f('ix_issb_climate_risk_exposures_reporting_unit_id'), table_name='issb_climate_risk_exposures')
    op.drop_index(op.f('ix_issb_climate_risk_exposures_id'), table_name='issb_climate_risk_exposures')
    op.drop_index('idx_issb_risk_unit_type_horizon', table_name='issb_climate_risk_exposures')
    op.drop_index('idx_issb_risk_tenant_unit', table_name='issb_climate_risk_exposures')
    op.drop_index('idx_issb_risk_tenant_type', table_name='issb_climate_risk_exposures')
    op.drop_index('idx_issb_risk_tenant_horizon', table_name='issb_climate_risk_exposures')
    op.drop_table('issb_climate_risk_exposures')
    op.drop_index(op.f('ix_issb_scenarios_tenant_id'), table_name='issb_scenarios')
    op.drop_index(op.f('ix_issb_scenarios_id'), table_name='issb_scenarios')
    op.drop_index('idx_issb_scenario_tenant_temp', table_name='issb_scenarios')
    op.drop_index('idx_issb_scenario_tenant_name', table_name='issb_scenarios')
    op.drop_index('idx_issb_scenario_tenant_default', table_name='issb_scenarios')
    op.drop_table('issb_scenarios')
    op.drop_index(op.f('ix_issb_reporting_units_tenant_id'), table_name='issb_reporting_units')
    op.drop_index(op.f('ix_issb_reporting_units_parent_unit_id'), table_name='issb_reporting_units')
    op.drop_index(op.f('ix_issb_reporting_units_id'), table_name='issb_reporting_units')
    op.drop_index('idx_issb_unit_tenant_parent', table_name='issb_reporting_units')
    op.drop_index('idx_issb_unit_tenant_name', table_name='issb_reporting_units')
    op.drop_index('idx_issb_unit_tenant_active', table_name='issb_reporting_units')
    op.drop_table('issb_reporting_units')
    # ### end Alembic commands ###
