# app/db/seeds/emission_factors_seed.py
"""
Core Emission Factors Seed

Seeds emission_factors table with DEFRA 2024 (UK) Scope 1/2/3 factors
for key categories: electricity, natural gas, diesel, petrol, flights, freight.
"""
import logging
from datetime import datetime
from sqlalchemy.orm import Session

from app.models.emission_factor import EmissionFactor

logger = logging.getLogger(__name__)


# =============================================================================
# DEFRA 2024 EMISSION FACTORS
# =============================================================================
# Source: UK Government GHG Conversion Factors for Company Reporting 2024
# https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2024

DEFRA_2024_FACTORS = [
    # =========================================================================
    # SCOPE 1 - STATIONARY COMBUSTION (FUELS)
    # =========================================================================
    # Natural Gas
    {
        "scope": "SCOPE_1",
        "category": "stationary_combustion",
        "activity_type": "natural_gas",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.18293,
        "unit": "kgCO2e/kWh",
        "source": "DEFRA 2024 - Natural Gas (Net CV)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "stationary_combustion",
        "activity_type": "natural_gas",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.18293,
        "unit": "kgCO2e/kWh",
        "source": "DEFRA 2024 - Natural Gas (Net CV) - Global fallback",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "stationary_combustion",
        "activity_type": "natural_gas_m3",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 2.02145,
        "unit": "kgCO2e/m3",
        "source": "DEFRA 2024 - Natural Gas per cubic metre",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # LPG
    {
        "scope": "SCOPE_1",
        "category": "stationary_combustion",
        "activity_type": "lpg",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.21445,
        "unit": "kgCO2e/kWh",
        "source": "DEFRA 2024 - LPG (Net CV)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "stationary_combustion",
        "activity_type": "lpg_litres",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 1.55573,
        "unit": "kgCO2e/litre",
        "source": "DEFRA 2024 - LPG per litre",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # Heating Oil / Gas Oil
    {
        "scope": "SCOPE_1",
        "category": "stationary_combustion",
        "activity_type": "gas_oil",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.25678,
        "unit": "kgCO2e/kWh",
        "source": "DEFRA 2024 - Gas Oil (Net CV)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "stationary_combustion",
        "activity_type": "heating_oil_litres",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 2.54064,
        "unit": "kgCO2e/litre",
        "source": "DEFRA 2024 - Heating Oil per litre",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # Coal
    {
        "scope": "SCOPE_1",
        "category": "stationary_combustion",
        "activity_type": "coal_industrial",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.32301,
        "unit": "kgCO2e/kWh",
        "source": "DEFRA 2024 - Coal (industrial)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },

    # =========================================================================
    # SCOPE 1 - MOBILE COMBUSTION (TRANSPORT FUELS)
    # =========================================================================
    # Diesel
    {
        "scope": "SCOPE_1",
        "category": "mobile_combustion",
        "activity_type": "diesel",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 2.51253,
        "unit": "kgCO2e/litre",
        "source": "DEFRA 2024 - Diesel (100% mineral diesel)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "mobile_combustion",
        "activity_type": "diesel",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 2.51253,
        "unit": "kgCO2e/litre",
        "source": "DEFRA 2024 - Diesel - Global fallback",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # Petrol / Gasoline
    {
        "scope": "SCOPE_1",
        "category": "mobile_combustion",
        "activity_type": "petrol",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 2.16236,
        "unit": "kgCO2e/litre",
        "source": "DEFRA 2024 - Petrol (100% mineral petrol)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "mobile_combustion",
        "activity_type": "petrol",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 2.16236,
        "unit": "kgCO2e/litre",
        "source": "DEFRA 2024 - Petrol - Global fallback",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "mobile_combustion",
        "activity_type": "gasoline",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 2.16236,
        "unit": "kgCO2e/litre",
        "source": "DEFRA 2024 - Gasoline/Petrol",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # Biofuels
    {
        "scope": "SCOPE_1",
        "category": "mobile_combustion",
        "activity_type": "biodiesel",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.03691,
        "unit": "kgCO2e/litre",
        "source": "DEFRA 2024 - Biodiesel ME (used cooking oil)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "mobile_combustion",
        "activity_type": "bioethanol",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.02758,
        "unit": "kgCO2e/litre",
        "source": "DEFRA 2024 - Bioethanol",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },

    # =========================================================================
    # SCOPE 1 - VEHICLE DISTANCE BASED
    # =========================================================================
    # Company cars by size
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "car_small_petrol",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.14957,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Small car, petrol",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "car_medium_petrol",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.18985,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Medium car, petrol",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "car_large_petrol",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.28380,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Large car, petrol",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "car_small_diesel",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.14087,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Small car, diesel",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "car_medium_diesel",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.17082,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Medium car, diesel",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "car_large_diesel",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.21266,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Large car, diesel",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "car_average",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.17129,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Average car (unknown fuel)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "car_average",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.17129,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Average car - Global fallback",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # Vans
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "van_small",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.14996,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Van, class I (up to 1.305 tonnes)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "van_medium",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.18870,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Van, class II (1.305 to 1.74 tonnes)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "van_large",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.26913,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Van, class III (1.74 to 3.5 tonnes)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "van_average",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.24018,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Van, average (diesel)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # HGV
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "hgv_rigid_small",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.49605,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - HGV rigid >3.5-7.5 tonnes",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "hgv_rigid_medium",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.62684,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - HGV rigid >7.5-17 tonnes",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "hgv_rigid_large",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.91073,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - HGV rigid >17 tonnes",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_1",
        "category": "company_vehicles",
        "activity_type": "hgv_articulated",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.92962,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - HGV articulated >33 tonnes",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },

    # =========================================================================
    # SCOPE 2 - ELECTRICITY
    # =========================================================================
    # UK Grid
    {
        "scope": "SCOPE_2",
        "category": "electricity",
        "activity_type": "grid_electricity",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.20707,
        "unit": "kgCO2e/kWh",
        "source": "DEFRA 2024 - UK Grid electricity",
        "method": "location_based",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_2",
        "category": "electricity",
        "activity_type": "grid_electricity_transmission",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.01827,
        "unit": "kgCO2e/kWh",
        "source": "DEFRA 2024 - T&D losses (UK)",
        "method": "location_based",
        "regulation": "GHG_PROTOCOL",
    },
    # Global/Regional defaults
    {
        "scope": "SCOPE_2",
        "category": "electricity",
        "activity_type": "grid_electricity",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.40000,
        "unit": "kgCO2e/kWh",
        "source": "IEA Global average (2022 data)",
        "method": "location_based",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_2",
        "category": "electricity",
        "activity_type": "grid_electricity",
        "country_code": "US",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.37020,
        "unit": "kgCO2e/kWh",
        "source": "EPA eGRID 2024 - US average",
        "method": "location_based",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_2",
        "category": "electricity",
        "activity_type": "grid_electricity",
        "country_code": "DE",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.38500,
        "unit": "kgCO2e/kWh",
        "source": "Germany grid factor 2024",
        "method": "location_based",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_2",
        "category": "electricity",
        "activity_type": "grid_electricity",
        "country_code": "FR",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.05200,
        "unit": "kgCO2e/kWh",
        "source": "France grid factor 2024 (nuclear)",
        "method": "location_based",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_2",
        "category": "electricity",
        "activity_type": "grid_electricity",
        "country_code": "CN",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.58100,
        "unit": "kgCO2e/kWh",
        "source": "China grid factor 2024",
        "method": "location_based",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_2",
        "category": "electricity",
        "activity_type": "grid_electricity",
        "country_code": "IN",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.70900,
        "unit": "kgCO2e/kWh",
        "source": "India grid factor 2024",
        "method": "location_based",
        "regulation": "GHG_PROTOCOL",
    },

    # =========================================================================
    # SCOPE 3 - BUSINESS TRAVEL (FLIGHTS)
    # =========================================================================
    # Domestic flights
    {
        "scope": "SCOPE_3",
        "category": "business_travel",
        "activity_type": "flight_domestic",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.24587,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Domestic flights (average passenger)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "business_travel",
        "activity_type": "flight_domestic",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.24587,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Domestic flights - Global fallback",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # Short-haul international (economy)
    {
        "scope": "SCOPE_3",
        "category": "business_travel",
        "activity_type": "flight_short_haul_economy",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.15298,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Short-haul international, economy",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "business_travel",
        "activity_type": "flight_short_haul_economy",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.15298,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Short-haul international, economy - Global fallback",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # Short-haul business
    {
        "scope": "SCOPE_3",
        "category": "business_travel",
        "activity_type": "flight_short_haul_business",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.22947,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Short-haul international, business",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # Long-haul economy
    {
        "scope": "SCOPE_3",
        "category": "business_travel",
        "activity_type": "flight_long_haul_economy",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.14615,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Long-haul international, economy",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "business_travel",
        "activity_type": "flight_long_haul_economy",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.14615,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Long-haul international, economy - Global fallback",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # Long-haul premium economy
    {
        "scope": "SCOPE_3",
        "category": "business_travel",
        "activity_type": "flight_long_haul_premium",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.23384,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Long-haul international, premium economy",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # Long-haul business
    {
        "scope": "SCOPE_3",
        "category": "business_travel",
        "activity_type": "flight_long_haul_business",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.42383,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Long-haul international, business",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "business_travel",
        "activity_type": "flight_long_haul_business",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.42383,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Long-haul international, business - Global fallback",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # Long-haul first class
    {
        "scope": "SCOPE_3",
        "category": "business_travel",
        "activity_type": "flight_long_haul_first",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.58460,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Long-haul international, first class",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },

    # =========================================================================
    # SCOPE 3 - FREIGHT / LOGISTICS
    # =========================================================================
    # Road freight
    {
        "scope": "SCOPE_3",
        "category": "freight",
        "activity_type": "road_freight_hgv",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.10478,
        "unit": "kgCO2e/tonne-km",
        "source": "DEFRA 2024 - HGV (all diesel), average laden",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "freight",
        "activity_type": "road_freight_hgv",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.10478,
        "unit": "kgCO2e/tonne-km",
        "source": "DEFRA 2024 - Road freight HGV - Global fallback",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "freight",
        "activity_type": "road_freight_van",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.60583,
        "unit": "kgCO2e/tonne-km",
        "source": "DEFRA 2024 - Van (class III, up to 3.5t), average laden",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # Rail freight
    {
        "scope": "SCOPE_3",
        "category": "freight",
        "activity_type": "rail_freight",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.02564,
        "unit": "kgCO2e/tonne-km",
        "source": "DEFRA 2024 - Rail freight",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "freight",
        "activity_type": "rail_freight",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.02564,
        "unit": "kgCO2e/tonne-km",
        "source": "DEFRA 2024 - Rail freight - Global fallback",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # Sea freight
    {
        "scope": "SCOPE_3",
        "category": "freight",
        "activity_type": "sea_freight_container",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.01609,
        "unit": "kgCO2e/tonne-km",
        "source": "DEFRA 2024 - Container ship (average)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "freight",
        "activity_type": "sea_freight_bulk",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.00416,
        "unit": "kgCO2e/tonne-km",
        "source": "DEFRA 2024 - Bulk carrier (average)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "freight",
        "activity_type": "sea_freight_tanker",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.00503,
        "unit": "kgCO2e/tonne-km",
        "source": "DEFRA 2024 - General cargo tanker",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    # Air freight
    {
        "scope": "SCOPE_3",
        "category": "freight",
        "activity_type": "air_freight_domestic",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 2.56628,
        "unit": "kgCO2e/tonne-km",
        "source": "DEFRA 2024 - Domestic air freight",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "freight",
        "activity_type": "air_freight_short_haul",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 1.59779,
        "unit": "kgCO2e/tonne-km",
        "source": "DEFRA 2024 - Short-haul international air freight",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "freight",
        "activity_type": "air_freight_long_haul",
        "country_code": "GLOBAL",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.60473,
        "unit": "kgCO2e/tonne-km",
        "source": "DEFRA 2024 - Long-haul international air freight",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },

    # =========================================================================
    # SCOPE 3 - EMPLOYEE COMMUTING
    # =========================================================================
    {
        "scope": "SCOPE_3",
        "category": "employee_commuting",
        "activity_type": "car_average",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.17129,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Average car",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "employee_commuting",
        "activity_type": "bus_average",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.10275,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Average local bus",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "employee_commuting",
        "activity_type": "rail_national",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.03549,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - National rail",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "employee_commuting",
        "activity_type": "rail_underground",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.02781,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Light rail and tram / Underground",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "employee_commuting",
        "activity_type": "taxi",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.14934,
        "unit": "kgCO2e/km",
        "source": "DEFRA 2024 - Regular taxi",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "employee_commuting",
        "activity_type": "bicycle",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.0,
        "unit": "kgCO2e/km",
        "source": "Zero emissions - cycling",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "employee_commuting",
        "activity_type": "walking",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.0,
        "unit": "kgCO2e/km",
        "source": "Zero emissions - walking",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "employee_commuting",
        "activity_type": "working_from_home",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.30000,
        "unit": "kgCO2e/day",
        "source": "Estimated WFH emissions (heating, electricity)",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },

    # =========================================================================
    # SCOPE 3 - WASTE
    # =========================================================================
    {
        "scope": "SCOPE_3",
        "category": "waste",
        "activity_type": "waste_landfill",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.58600,
        "unit": "kgCO2e/kg",
        "source": "DEFRA 2024 - Mixed waste to landfill",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "waste",
        "activity_type": "waste_recycling",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.02100,
        "unit": "kgCO2e/kg",
        "source": "DEFRA 2024 - Mixed waste recycled",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "waste",
        "activity_type": "waste_incineration",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.02100,
        "unit": "kgCO2e/kg",
        "source": "DEFRA 2024 - Mixed waste combustion",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "waste",
        "activity_type": "waste_paper_recycling",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.02100,
        "unit": "kgCO2e/kg",
        "source": "DEFRA 2024 - Paper/card recycled",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "waste",
        "activity_type": "waste_plastic_recycling",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.02100,
        "unit": "kgCO2e/kg",
        "source": "DEFRA 2024 - Mixed plastics recycled",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },

    # =========================================================================
    # SCOPE 3 - WATER
    # =========================================================================
    {
        "scope": "SCOPE_3",
        "category": "water",
        "activity_type": "water_supply",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.14900,
        "unit": "kgCO2e/m3",
        "source": "DEFRA 2024 - Water supply",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
    {
        "scope": "SCOPE_3",
        "category": "water",
        "activity_type": "water_treatment",
        "country_code": "GB",
        "year": 2024,
        "dataset": "DEFRA_2024",
        "factor": 0.27200,
        "unit": "kgCO2e/m3",
        "source": "DEFRA 2024 - Water treatment",
        "method": "average_data",
        "regulation": "GHG_PROTOCOL",
    },
]


def seed_emission_factors(db: Session) -> int:
    """
    Seed core emission factors from DEFRA 2024.

    Returns number of factors inserted.
    """
    inserted = 0
    for factor_data in DEFRA_2024_FACTORS:
        # Check if already exists
        existing = db.query(EmissionFactor).filter(
            EmissionFactor.scope == factor_data["scope"],
            EmissionFactor.category == factor_data["category"],
            EmissionFactor.activity_type == factor_data["activity_type"],
            EmissionFactor.country_code == factor_data["country_code"],
            EmissionFactor.year == factor_data["year"],
            EmissionFactor.dataset == factor_data["dataset"],
        ).first()

        if not existing:
            factor = EmissionFactor(
                scope=factor_data["scope"],
                category=factor_data["category"],
                activity_type=factor_data["activity_type"],
                country_code=factor_data["country_code"],
                year=factor_data["year"],
                dataset=factor_data["dataset"],
                factor=factor_data["factor"],
                unit=factor_data["unit"],
                source=factor_data.get("source"),
                method=factor_data.get("method", "average_data"),
                regulation=factor_data.get("regulation", "GHG_PROTOCOL"),
            )
            db.add(factor)
            inserted += 1

    db.commit()
    logger.info(f"Emission Factors (DEFRA 2024): Inserted {inserted} new factors")
    return inserted


def run_emission_factors_seed(db: Session) -> dict:
    """
    Run emission factors seed.

    Returns summary of inserted records.
    """
    logger.info("Starting emission factors seed...")

    factors = seed_emission_factors(db)

    summary = {
        "emission_factors": factors,
    }

    logger.info(f"Emission factors seed complete: {summary}")
    return summary
